services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  # flowise:
  #   image: flowiseai/flowise:latest
  #   restart: always
  #   ports:
  #     - "3100:3000"
  #   environment:
  #     - PORT=3000
  #   volumes:
  #     - ./flowise-data:/root/.flowise